# -*- coding: utf-8 -*-
"""VaishnaviKhade_NLP_Bag-of-words.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1otqitAWdYwPasAtrKOVlEgCukRZTm2sE

** Bag-of-words **
"""

!pip install gensim

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Sample Corpus
corpus = [
    'the cat sat on the mat',
    'the dog sat on the log',
    'cats and dogs are great'
]

# 1. Count Occurrence (Raw Counts)
vectorizer = CountVectorizer()
X_counts = vectorizer.fit_transform(corpus)

# 2. Normalized Count Occurrence (Term Frequency)
# We divide the counts by the sum of words in the document
from sklearn.preprocessing import normalize
X_normalized = normalize(X_counts, norm='l1', axis=1)

# Display as a Table
df_counts = pd.DataFrame(X_counts.toarray(), columns=vectorizer.get_feature_names_out())
print("Raw Count Occurrence:")
print(df_counts)

print("\nNormalized Count (TF):")
print(pd.DataFrame(X_normalized.toarray(), columns=vectorizer.get_feature_names_out()))

"""**TF-IDF (Term Frequency-Inverse Document Frequency)**"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(corpus)

# Display result
df_tfidf = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())
print("TF-IDF Matrix:")
df_tfidf

"""**Word2Vec Embeddings**"""

from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
import nltk

# Fix: Download both punkt and punkt_tab
nltk.download('punkt')
nltk.download('punkt_tab')

# Sample Corpus
corpus = [
    'the cat sat on the mat',
    'the dog sat on the log',
    'cats and dogs are great'
]

# Preprocessing: Word2Vec needs a list of tokenized sentences
tokenized_corpus = [word_tokenize(sentence.lower()) for sentence in corpus]

# Train the Word2Vec model
model = Word2Vec(sentences=tokenized_corpus, vector_size=100, window=5, min_count=1, workers=4)

# Test the output
word = "cat"
print(f"Vector for '{word}':\n", model.wv[word][:10]) # Showing first 10 dimensions