# -*- coding: utf-8 -*-
"""VaishnaviKhade_NLP_Lab10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NL9uOxgvD0bnF4VZ1sTQHdzUPO1oxa8s

**Write a better auto-complete algorithm using an N-gram model (similar models are used for
translation, determining the author of a text, and speech recognition)**
"""

import nltk
from nltk.util import ngrams
from nltk.lm.preprocessing import padded_everygram_pipeline
from nltk.lm import MLE
from nltk.tokenize import word_tokenize

# Necessary resources
nltk.download('punkt')
nltk.download('punkt_tab')

# Sample training data (In a real app, you would load a large .txt file)
text_data = [
    "I need to go to the bank to deposit my paycheck",
    "I need to go to the river bank to fish",
    "The pilot had to bank the aircraft to the left",
    "Artificial intelligence is transforming the world",
    "Artificial intelligence is powerful and efficient"
]

# Preprocessing: Tokenize and lower-case
tokenized_text = [word_tokenize(sent.lower()) for sent in text_data]

print("[SUCCESS] Training data tokenized.")

# We use N=3 (Trigrams)
n = 3
train_data, padded_vocab = padded_everygram_pipeline(n, tokenized_text)

# Maximum Likelihood Estimator (MLE) is the standard algorithm for N-grams
model = MLE(n)
model.fit(train_data, padded_vocab)

print(f"[SUCCESS] {n}-gram model trained.")

def auto_complete(phrase, num_suggestions=3):
    # Tokenize and get the last (n-1) words
    tokens = word_tokenize(phrase.lower())
    context = tuple(tokens[-(n-1):])

    # Get all possible next words and their scores
    suggestions = []
    for word in model.vocab:
        score = model.score(word, context)
        if score > 0:
            suggestions.append((word, score))

    # Sort by probability (highest first)
    suggestions.sort(key=lambda x: x[1], reverse=True)
    return suggestions[:num_suggestions]

# --- Test the Algorithm ---
test_phrases = [
    "I need to",
    "Artificial intelligence",
    "The pilot had"
]

print(f"{'INPUT PHRASE':<25} | {'TOP SUGGESTIONS (Word, Probability)'}")
print("-" * 75)

for p in test_phrases:
    results = auto_complete(p)
    print(f"{p:<25} | {results}")