# -*- coding: utf-8 -*-
"""Vaishnavikhade_NLP_Lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BhA_siBOyX2V31rhfXOxU-A4m9bBOco

**Installation and Resource Loading**

Before processing text, NLTK requires specific "corpora" (linguistic datasets) to understand English grammar and word roots.
"""

import nltk
import pandas as pd
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer
from nltk.sentiment import SentimentIntensityAnalyzer
from nltk import pos_tag

# Future-proofing: Downloading specific resources for Python 3.12+
resources = [
    'punkt', 'punkt_tab', 'stopwords', 'wordnet',
    'omw-1.4', 'averaged_perceptron_tagger_eng', 'vader_lexicon'
]

for res in resources:
    nltk.download(res, quiet=True)

print("✅ Environment Ready: Resources (including punkt_tab) loaded successfully.")

"""**The Contextual Mapping Engine**"""

def get_wordnet_pos(tag):
    """Maps NLTK Treebank POS tags to WordNet-friendly constants."""
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

"""**The Integrated Preprocessing Pipeline**

This cell represents the core logic of the application. It cleans the text and evaluates the "emotional temperature" of the content.
"""

def analyze_text_pipeline(text):
    # 1. Innovation: Sentiment Analysis (VADER)
    sia = SentimentIntensityAnalyzer()
    sentiment = sia.polarity_scores(text)

    # 2. Tokenization and Noise Removal
    tokens = word_tokenize(text.lower())
    stop_words = set(stopwords.words('english'))
    # Filter to keep only alphabetic words and remove common 'stop words'
    filtered = [w for w in tokens if w.isalpha() and w not in stop_words]

    # 3. POS Tagging
    tagged = pos_tag(filtered)

    # 4. Contextual Lemmatization
    lemmatizer = WordNetLemmatizer()
    processed_list = []

    for word, tag in tagged:
        lemma = lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        processed_list.append({
            "Original": word,
            "Lemma": lemma,
            "POS": tag
        })

    return pd.DataFrame(processed_list), sentiment

"""**Statistical Visualization**"""

def generate_dashboard(df, sentiment):
    # Output 1: Sentiment Summary
    mood_score = sentiment['compound']
    mood = "Positive" if mood_score >= 0.05 else "Negative" if mood_score <= -0.05 else "Neutral"

    print(f"--- Analysis Report ---")
    print(f"Detected Mood: {mood} (Score: {mood_score})")
    print(f"Lexical Diversity: {(df['Lemma'].nunique() / len(df) * 100):.2f}%")

    # Output 2: POS Distribution Graph
    plt.figure(figsize=(10, 5))
    df['POS'].value_counts().plot(kind='bar', color=['#4CAF50', '#2196F3', '#FF9800', '#f44336'])
    plt.title("Grammatical Composition (POS Tag Counts)")
    plt.ylabel("Frequency")
    plt.show()

    # Output 3: Top Keywords
    print("\n--- Top 5 Key Root Words ---")
    print(df['Lemma'].value_counts().head(5))

"""**Application Execution**"""

# Test text with a mix of tones and grammar
sample_input = """
NLTK is an amazing library for natural language processing!
While some errors can be annoying to fix, the results are incredibly rewarding.
Developers are building smarter applications every day.
"""

# Run the Lab
df_results, sentiment_data = analyze_text_pipeline(sample_input)

# Launch Dashboard
generate_dashboard(df_results, sentiment_data)

# Show the cleaned data table
print("\n--- Processed Tokens Sample ---")
df_results.head(10)